// Mocks generated by Mockito 5.4.6 from annotations
// in rockserwis_podcaster/test/providers/podcast_sync_helper_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:http/http.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i10;
import 'package:rockserwis_podcaster/models/episode.dart' as _i8;
import 'package:rockserwis_podcaster/models/podcast.dart' as _i6;
import 'package:rockserwis_podcaster/objectbox.g.dart' as _i3;
import 'package:rockserwis_podcaster/providers/episode_repository.dart' as _i7;
import 'package:rockserwis_podcaster/providers/objectbox_repository.dart'
    as _i9;
import 'package:rockserwis_podcaster/providers/podcast_repository.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeClient_0 extends _i1.SmartFake implements _i2.Client {
  _FakeClient_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStore_1 extends _i1.SmartFake implements _i3.Store {
  _FakeStore_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBox_2<T> extends _i1.SmartFake implements _i3.Box<T> {
  _FakeBox_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFuture_3<T1> extends _i1.SmartFake implements _i4.Future<T1> {
  _FakeFuture_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeQueryBuilder_4<T1> extends _i1.SmartFake
    implements _i3.QueryBuilder<T1> {
  _FakeQueryBuilder_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePropertyQuery_5<T1> extends _i1.SmartFake
    implements _i3.PropertyQuery<T1> {
  _FakePropertyQuery_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeQuery_6<T1> extends _i1.SmartFake implements _i3.Query<T1> {
  _FakeQuery_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PodcastJsonRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPodcastJsonRepository extends _i1.Mock
    implements _i5.PodcastJsonRepository {
  MockPodcastJsonRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Client get client =>
      (super.noSuchMethod(
            Invocation.getter(#client),
            returnValue: _FakeClient_0(this, Invocation.getter(#client)),
          )
          as _i2.Client);

  @override
  _i4.Future<List<_i6.Podcast>> fetchPodcasts() =>
      (super.noSuchMethod(
            Invocation.method(#fetchPodcasts, []),
            returnValue: _i4.Future<List<_i6.Podcast>>.value(<_i6.Podcast>[]),
          )
          as _i4.Future<List<_i6.Podcast>>);
}

/// A class which mocks [EpisodeRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockEpisodeRepository extends _i1.Mock implements _i7.EpisodeRepository {
  MockEpisodeRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Client get client =>
      (super.noSuchMethod(
            Invocation.getter(#client),
            returnValue: _FakeClient_0(this, Invocation.getter(#client)),
          )
          as _i2.Client);

  @override
  _i4.Future<List<_i8.Episode>> fetchEpisodes(int? podcastId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchEpisodes, [podcastId]),
            returnValue: _i4.Future<List<_i8.Episode>>.value(<_i8.Episode>[]),
          )
          as _i4.Future<List<_i8.Episode>>);
}

/// A class which mocks [ObjectBox].
///
/// See the documentation for Mockito's code generation for more information.
class MockObjectBox extends _i1.Mock implements _i9.ObjectBox {
  MockObjectBox() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Store get store =>
      (super.noSuchMethod(
            Invocation.getter(#store),
            returnValue: _FakeStore_1(this, Invocation.getter(#store)),
          )
          as _i3.Store);

  @override
  _i3.Box<_i6.Podcast> get podcastBox =>
      (super.noSuchMethod(
            Invocation.getter(#podcastBox),
            returnValue: _FakeBox_2<_i6.Podcast>(
              this,
              Invocation.getter(#podcastBox),
            ),
          )
          as _i3.Box<_i6.Podcast>);

  @override
  _i3.Box<_i8.Episode> get episodeBox =>
      (super.noSuchMethod(
            Invocation.getter(#episodeBox),
            returnValue: _FakeBox_2<_i8.Episode>(
              this,
              Invocation.getter(#episodeBox),
            ),
          )
          as _i3.Box<_i8.Episode>);

  @override
  set store(_i3.Store? value) => super.noSuchMethod(
    Invocation.setter(#store, value),
    returnValueForMissingStub: null,
  );

  @override
  set podcastBox(_i3.Box<_i6.Podcast>? value) => super.noSuchMethod(
    Invocation.setter(#podcastBox, value),
    returnValueForMissingStub: null,
  );

  @override
  set episodeBox(_i3.Box<_i8.Episode>? value) => super.noSuchMethod(
    Invocation.setter(#episodeBox, value),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [Box].
///
/// See the documentation for Mockito's code generation for more information.
class MockBox<T> extends _i1.Mock implements _i3.Box<T> {
  MockBox() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int put(T? object, {_i3.PutMode? mode = _i3.PutMode.put}) =>
      (super.noSuchMethod(
            Invocation.method(#put, [object], {#mode: mode}),
            returnValue: 0,
          )
          as int);

  @override
  _i4.Future<int> putAsync(T? object, {_i3.PutMode? mode = _i3.PutMode.put}) =>
      (super.noSuchMethod(
            Invocation.method(#putAsync, [object], {#mode: mode}),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<T> putAndGetAsync(
    T? object, {
    _i3.PutMode? mode = _i3.PutMode.put,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#putAndGetAsync, [object], {#mode: mode}),
            returnValue:
                _i10.ifNotNull(
                  _i10.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#putAndGetAsync, [object], {#mode: mode}),
                  ),
                  (T v) => _i4.Future<T>.value(v),
                ) ??
                _FakeFuture_3<T>(
                  this,
                  Invocation.method(#putAndGetAsync, [object], {#mode: mode}),
                ),
          )
          as _i4.Future<T>);

  @override
  _i4.Future<int> putQueuedAwaitResult(
    T? object, {
    _i3.PutMode? mode = _i3.PutMode.put,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#putQueuedAwaitResult, [object], {#mode: mode}),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  int putQueued(T? object, {_i3.PutMode? mode = _i3.PutMode.put}) =>
      (super.noSuchMethod(
            Invocation.method(#putQueued, [object], {#mode: mode}),
            returnValue: 0,
          )
          as int);

  @override
  List<int> putMany(List<T>? objects, {_i3.PutMode? mode = _i3.PutMode.put}) =>
      (super.noSuchMethod(
            Invocation.method(#putMany, [objects], {#mode: mode}),
            returnValue: <int>[],
          )
          as List<int>);

  @override
  _i4.Future<List<int>> putManyAsync(
    List<T>? objects, {
    _i3.PutMode? mode = _i3.PutMode.put,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#putManyAsync, [objects], {#mode: mode}),
            returnValue: _i4.Future<List<int>>.value(<int>[]),
          )
          as _i4.Future<List<int>>);

  @override
  _i4.Future<List<T>> putAndGetManyAsync(
    List<T>? objects, {
    _i3.PutMode? mode = _i3.PutMode.put,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#putAndGetManyAsync, [objects], {#mode: mode}),
            returnValue: _i4.Future<List<T>>.value(<T>[]),
          )
          as _i4.Future<List<T>>);

  @override
  T? get(int? id) => (super.noSuchMethod(Invocation.method(#get, [id])) as T?);

  @override
  _i4.Future<T?> getAsync(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getAsync, [id]),
            returnValue: _i4.Future<T?>.value(),
          )
          as _i4.Future<T?>);

  @override
  List<T?> getMany(List<int>? ids, {bool? growableResult = false}) =>
      (super.noSuchMethod(
            Invocation.method(
              #getMany,
              [ids],
              {#growableResult: growableResult},
            ),
            returnValue: <T?>[],
          )
          as List<T?>);

  @override
  _i4.Future<List<T?>> getManyAsync(
    List<int>? ids, {
    bool? growableResult = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getManyAsync,
              [ids],
              {#growableResult: growableResult},
            ),
            returnValue: _i4.Future<List<T?>>.value(<T?>[]),
          )
          as _i4.Future<List<T?>>);

  @override
  List<T> getAll() =>
      (super.noSuchMethod(Invocation.method(#getAll, []), returnValue: <T>[])
          as List<T>);

  @override
  _i4.Future<List<T>> getAllAsync() =>
      (super.noSuchMethod(
            Invocation.method(#getAllAsync, []),
            returnValue: _i4.Future<List<T>>.value(<T>[]),
          )
          as _i4.Future<List<T>>);

  @override
  _i3.QueryBuilder<T> query([_i3.Condition<T>? qc]) =>
      (super.noSuchMethod(
            Invocation.method(#query, [qc]),
            returnValue: _FakeQueryBuilder_4<T>(
              this,
              Invocation.method(#query, [qc]),
            ),
          )
          as _i3.QueryBuilder<T>);

  @override
  int count({int? limit = 0}) =>
      (super.noSuchMethod(
            Invocation.method(#count, [], {#limit: limit}),
            returnValue: 0,
          )
          as int);

  @override
  bool isEmpty() =>
      (super.noSuchMethod(Invocation.method(#isEmpty, []), returnValue: false)
          as bool);

  @override
  bool contains(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#contains, [id]),
            returnValue: false,
          )
          as bool);

  @override
  bool containsMany(List<int>? ids) =>
      (super.noSuchMethod(
            Invocation.method(#containsMany, [ids]),
            returnValue: false,
          )
          as bool);

  @override
  bool remove(int? id) =>
      (super.noSuchMethod(Invocation.method(#remove, [id]), returnValue: false)
          as bool);

  @override
  _i4.Future<bool> removeAsync(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#removeAsync, [id]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  int removeMany(List<int>? ids) =>
      (super.noSuchMethod(Invocation.method(#removeMany, [ids]), returnValue: 0)
          as int);

  @override
  _i4.Future<int> removeManyAsync(List<int>? ids) =>
      (super.noSuchMethod(
            Invocation.method(#removeManyAsync, [ids]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  int removeAll() =>
      (super.noSuchMethod(Invocation.method(#removeAll, []), returnValue: 0)
          as int);

  @override
  _i4.Future<int> removeAllAsync() =>
      (super.noSuchMethod(
            Invocation.method(#removeAllAsync, []),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);
}

/// A class which mocks [Query].
///
/// See the documentation for Mockito's code generation for more information.
class MockQuery<T> extends _i1.Mock implements _i3.Query<T> {
  MockQuery() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get entityId =>
      (super.noSuchMethod(Invocation.getter(#entityId), returnValue: 0) as int);

  @override
  set offset(int? offset) => super.noSuchMethod(
    Invocation.setter(#offset, offset),
    returnValueForMissingStub: null,
  );

  @override
  set limit(int? limit) => super.noSuchMethod(
    Invocation.setter(#limit, limit),
    returnValueForMissingStub: null,
  );

  @override
  int count() =>
      (super.noSuchMethod(Invocation.method(#count, []), returnValue: 0)
          as int);

  @override
  int remove() =>
      (super.noSuchMethod(Invocation.method(#remove, []), returnValue: 0)
          as int);

  @override
  _i4.Future<int> removeAsync() =>
      (super.noSuchMethod(
            Invocation.method(#removeAsync, []),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  void close() => super.noSuchMethod(
    Invocation.method(#close, []),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<T?> findFirstAsync() =>
      (super.noSuchMethod(
            Invocation.method(#findFirstAsync, []),
            returnValue: _i4.Future<T?>.value(),
          )
          as _i4.Future<T?>);

  @override
  _i4.Future<T?> findUniqueAsync() =>
      (super.noSuchMethod(
            Invocation.method(#findUniqueAsync, []),
            returnValue: _i4.Future<T?>.value(),
          )
          as _i4.Future<T?>);

  @override
  List<int> findIds() =>
      (super.noSuchMethod(Invocation.method(#findIds, []), returnValue: <int>[])
          as List<int>);

  @override
  _i4.Future<List<int>> findIdsAsync() =>
      (super.noSuchMethod(
            Invocation.method(#findIdsAsync, []),
            returnValue: _i4.Future<List<int>>.value(<int>[]),
          )
          as _i4.Future<List<int>>);

  @override
  List<T> find() =>
      (super.noSuchMethod(Invocation.method(#find, []), returnValue: <T>[])
          as List<T>);

  @override
  _i4.Future<List<T>> findAsync() =>
      (super.noSuchMethod(
            Invocation.method(#findAsync, []),
            returnValue: _i4.Future<List<T>>.value(<T>[]),
          )
          as _i4.Future<List<T>>);

  @override
  List<_i3.IdWithScore> findIdsWithScores() =>
      (super.noSuchMethod(
            Invocation.method(#findIdsWithScores, []),
            returnValue: <_i3.IdWithScore>[],
          )
          as List<_i3.IdWithScore>);

  @override
  _i4.Future<List<_i3.IdWithScore>> findIdsWithScoresAsync() =>
      (super.noSuchMethod(
            Invocation.method(#findIdsWithScoresAsync, []),
            returnValue: _i4.Future<List<_i3.IdWithScore>>.value(
              <_i3.IdWithScore>[],
            ),
          )
          as _i4.Future<List<_i3.IdWithScore>>);

  @override
  List<_i3.ObjectWithScore<T>> findWithScores() =>
      (super.noSuchMethod(
            Invocation.method(#findWithScores, []),
            returnValue: <_i3.ObjectWithScore<T>>[],
          )
          as List<_i3.ObjectWithScore<T>>);

  @override
  _i4.Future<List<_i3.ObjectWithScore<T>>> findWithScoresAsync() =>
      (super.noSuchMethod(
            Invocation.method(#findWithScoresAsync, []),
            returnValue: _i4.Future<List<_i3.ObjectWithScore<T>>>.value(
              <_i3.ObjectWithScore<T>>[],
            ),
          )
          as _i4.Future<List<_i3.ObjectWithScore<T>>>);

  @override
  _i4.Stream<T> stream() =>
      (super.noSuchMethod(
            Invocation.method(#stream, []),
            returnValue: _i4.Stream<T>.empty(),
          )
          as _i4.Stream<T>);

  @override
  String describe() =>
      (super.noSuchMethod(
            Invocation.method(#describe, []),
            returnValue: _i10.dummyValue<String>(
              this,
              Invocation.method(#describe, []),
            ),
          )
          as String);

  @override
  String describeParameters() =>
      (super.noSuchMethod(
            Invocation.method(#describeParameters, []),
            returnValue: _i10.dummyValue<String>(
              this,
              Invocation.method(#describeParameters, []),
            ),
          )
          as String);

  @override
  _i3.PropertyQuery<DartType> property<DartType>(
    _i3.QueryProperty<T, DartType>? prop,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#property, [prop]),
            returnValue: _FakePropertyQuery_5<DartType>(
              this,
              Invocation.method(#property, [prop]),
            ),
          )
          as _i3.PropertyQuery<DartType>);
}

/// A class which mocks [QueryBuilder].
///
/// See the documentation for Mockito's code generation for more information.
class MockQueryBuilder<T> extends _i1.Mock implements _i3.QueryBuilder<T> {
  MockQueryBuilder() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Query<T> build() =>
      (super.noSuchMethod(
            Invocation.method(#build, []),
            returnValue: _FakeQuery_6<T>(this, Invocation.method(#build, [])),
          )
          as _i3.Query<T>);

  @override
  _i4.Stream<_i3.Query<T>> watch({bool? triggerImmediately = false}) =>
      (super.noSuchMethod(
            Invocation.method(#watch, [], {
              #triggerImmediately: triggerImmediately,
            }),
            returnValue: _i4.Stream<_i3.Query<T>>.empty(),
          )
          as _i4.Stream<_i3.Query<T>>);

  @override
  _i3.QueryBuilder<T> order<D>(_i3.QueryProperty<T, D>? p, {int? flags = 0}) =>
      (super.noSuchMethod(
            Invocation.method(#order, [p], {#flags: flags}),
            returnValue: _FakeQueryBuilder_4<T>(
              this,
              Invocation.method(#order, [p], {#flags: flags}),
            ),
          )
          as _i3.QueryBuilder<T>);

  @override
  link<TargetEntityT>(
    _i3.QueryRelationToOne<T, TargetEntityT>? rel, [
    _i3.Condition<TargetEntityT>? qc,
  ]) => throw UnsupportedError(
    r'"link" cannot be used without a mockito fallback generator.',
  );

  @override
  backlink<SourceEntityT>(
    _i3.QueryRelationToOne<SourceEntityT, T>? rel, [
    _i3.Condition<SourceEntityT>? qc,
  ]) => throw UnsupportedError(
    r'"backlink" cannot be used without a mockito fallback generator.',
  );

  @override
  linkMany<TargetEntityT>(
    _i3.QueryRelationToMany<T, TargetEntityT>? rel, [
    _i3.Condition<TargetEntityT>? qc,
  ]) => throw UnsupportedError(
    r'"linkMany" cannot be used without a mockito fallback generator.',
  );

  @override
  backlinkMany<SourceEntityT>(
    _i3.QueryRelationToMany<SourceEntityT, T>? rel, [
    _i3.Condition<SourceEntityT>? qc,
  ]) => throw UnsupportedError(
    r'"backlinkMany" cannot be used without a mockito fallback generator.',
  );
}
